/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-11 at 22:25:25 UTC 
 * Modify at your own risk.
 */

package softhealth.zombiecatch.userendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double experience;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lvlDeadly;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lvlPerceptive;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lvlSneaky;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lvlStrong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public User setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getExperience() {
    return experience;
  }

  /**
   * @param experience experience or {@code null} for none
   */
  public User setExperience(java.lang.Double experience) {
    this.experience = experience;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public User setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLvlDeadly() {
    return lvlDeadly;
  }

  /**
   * @param lvlDeadly lvlDeadly or {@code null} for none
   */
  public User setLvlDeadly(java.lang.Integer lvlDeadly) {
    this.lvlDeadly = lvlDeadly;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLvlPerceptive() {
    return lvlPerceptive;
  }

  /**
   * @param lvlPerceptive lvlPerceptive or {@code null} for none
   */
  public User setLvlPerceptive(java.lang.Integer lvlPerceptive) {
    this.lvlPerceptive = lvlPerceptive;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLvlSneaky() {
    return lvlSneaky;
  }

  /**
   * @param lvlSneaky lvlSneaky or {@code null} for none
   */
  public User setLvlSneaky(java.lang.Integer lvlSneaky) {
    this.lvlSneaky = lvlSneaky;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLvlStrong() {
    return lvlStrong;
  }

  /**
   * @param lvlStrong lvlStrong or {@code null} for none
   */
  public User setLvlStrong(java.lang.Integer lvlStrong) {
    this.lvlStrong = lvlStrong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public User setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public User setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
