/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-12 at 14:52:16 UTC 
 * Modify at your own risk.
 */

package softhealth.zombiecatch.gameendpoint.model;

/**
 * Model definition for Game.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gameendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Game extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double chopLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double chopLon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gameTitle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hostEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer maxPlayers;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pass;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double rad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double timeLeft;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getChopLat() {
    return chopLat;
  }

  /**
   * @param chopLat chopLat or {@code null} for none
   */
  public Game setChopLat(java.lang.Double chopLat) {
    this.chopLat = chopLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getChopLon() {
    return chopLon;
  }

  /**
   * @param chopLon chopLon or {@code null} for none
   */
  public Game setChopLon(java.lang.Double chopLon) {
    this.chopLon = chopLon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGameTitle() {
    return gameTitle;
  }

  /**
   * @param gameTitle gameTitle or {@code null} for none
   */
  public Game setGameTitle(java.lang.String gameTitle) {
    this.gameTitle = gameTitle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHostEmail() {
    return hostEmail;
  }

  /**
   * @param hostEmail hostEmail or {@code null} for none
   */
  public Game setHostEmail(java.lang.String hostEmail) {
    this.hostEmail = hostEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Game setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * @param lat lat or {@code null} for none
   */
  public Game setLat(java.lang.Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLon() {
    return lon;
  }

  /**
   * @param lon lon or {@code null} for none
   */
  public Game setLon(java.lang.Double lon) {
    this.lon = lon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMaxPlayers() {
    return maxPlayers;
  }

  /**
   * @param maxPlayers maxPlayers or {@code null} for none
   */
  public Game setMaxPlayers(java.lang.Integer maxPlayers) {
    this.maxPlayers = maxPlayers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPass() {
    return pass;
  }

  /**
   * @param pass pass or {@code null} for none
   */
  public Game setPass(java.lang.String pass) {
    this.pass = pass;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getRad() {
    return rad;
  }

  /**
   * @param rad rad or {@code null} for none
   */
  public Game setRad(java.lang.Double rad) {
    this.rad = rad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getTimeLeft() {
    return timeLeft;
  }

  /**
   * @param timeLeft timeLeft or {@code null} for none
   */
  public Game setTimeLeft(java.lang.Double timeLeft) {
    this.timeLeft = timeLeft;
    return this;
  }

  @Override
  public Game set(String fieldName, Object value) {
    return (Game) super.set(fieldName, value);
  }

  @Override
  public Game clone() {
    return (Game) super.clone();
  }

}
